services:
  sipi-etl:
    build: .
    container_name: sipi-etl-service
    environment:
      - DB_CONN_STRING=postgresql://sipi:sipi@db:5432/sipi
    command: ["python", "-m", "src.main", "--daemon", "--interval=24"]
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:15-3.3
    container_name: sipi-db
    environment:
      POSTGRES_DB: sipi
      POSTGRES_USER: sipi
      POSTGRES_PASSWORD: sipi
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sipi"]
      interval: 5s

volumes:
  pg_data:
